language: ruby
cache: bundler

rvm:
  - 2.3.3

services:
  - postgresql

before_script:
  - psql -c 'create database expense_tracker_test;' -U postgres

branches:
  only:
    - master
    - v1.0

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
