# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737403d3c04bf4a995bfc8594f986629e3d001c8c3ebc3e89f81594a555b5377428b7908a0a334cbe6bc6f88a610b6d1a3d23fb89516175327ab34f651cd31ba

test:
  secret_key_base: c038101e76f696df16e23cf7c0d52e8e589c15fc80abf401ab156d7b0a70316a4d02649792535acae3cbd3b5045463b82afc73cb72b371d0b78894a2991db217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
